(()=>{
  'use strict';
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nav=q('#nav'),workspace=q('.workspace');if(!nav||!workspace)return;
  nav.insertAdjacentHTML('beforeend','<button data-view="systemOptions" class="manager-only"><b>⚙</b><span>وضعیت‌ها و اولویت‌ها</span></button>');
  workspace.insertAdjacentHTML('beforeend',`<section id="systemOptionsView" class="view hidden manager-only"><div class="panel"><div class="panel-head"><div><h3>وضعیت‌ها و اولویت‌ها</h3><small>گزینه‌های فرم وظیفه و عنوان‌های شرایط دیرکرد را مدیریت کنید.</small></div></div><form id="optionForm" class="option-form"><label>گروه<select name="field_type"><option value="status">وضعیت وظیفه</option><option value="priority">اولویت</option><option value="due_state">شرایط دیرکرد</option></select></label><label>عنوان<input name="label" required></label><label>ترتیب<input name="sort_order" type="number" value="100"></label><button class="primary">افزودن</button></form><div class="table-wrap"><table><thead><tr><th>گروه</th><th>عنوان</th><th>ترتیب</th><th>فعال</th><th>عملیات</th></tr></thead><tbody id="optionBody"></tbody></table></div></div></section>`);
  let rows=[];const types={status:'وضعیت وظیفه',priority:'اولویت',due_state:'شرایط دیرکرد'};
  async function load(){rows=await select('task_field_options','select=*&order=field_type,sort_order,label');render();apply()}
  function render(){q('#optionBody').innerHTML=rows.map(x=>`<tr><td>${types[x.field_type]}</td><td>${esc(x.label)}</td><td>${fa(x.sort_order)}</td><td>${x.active?'بله':'خیر'}</td><td><button class="ghost option-toggle" data-id="${x.id}">${x.active?'غیرفعال':'فعال'}</button>${x.system_key?'':`<button class="danger option-delete" data-id="${x.id}">حذف</button>`}</td></tr>`).join('')}
  function apply(){const f=q('#taskForm');if(f)for(const field of ['status','priority']){const select=f.elements[field],available=rows.filter(x=>x.field_type===field&&x.active),current=select.value;if(available.length){select.innerHTML=available.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('');if(available.some(x=>x.value===current))select.value=current}}window.BAMCO_TASK_OPTIONS=rows;window.dispatchEvent(new CustomEvent('bamco-options-updated',{detail:rows}))}
  q('#optionForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.value=data.label=data.label.trim();data.sort_order=Number(data.sort_order||100);data.created_by=state.profile.id;try{await insert('task_field_options',data);e.currentTarget.reset();e.currentTarget.elements.sort_order.value=100;await load();toast('گزینه جدید ثبت شد.')}catch(err){toast(err.message,true)}});
  q('#optionBody').addEventListener('click',async e=>{const btn=e.target.closest('[data-id]');if(!btn)return;try{const row=rows.find(x=>String(x.id)===btn.dataset.id);if(btn.classList.contains('option-toggle'))await update('task_field_options',`id=eq.${row.id}`,{active:!row.active});else if(confirm(`گزینه «${row.label}» حذف شود؟`))await api(`/rest/v1/task_field_options?id=eq.${row.id}`,{method:'DELETE',prefer:'return=representation'});await load()}catch(err){toast(err.message,true)}});
  document.addEventListener('DOMContentLoaded',()=>{q('#nav').addEventListener('click',e=>{if(e.target.closest('[data-view="systemOptions"]'))setTimeout(load)});setTimeout(()=>{if(state?.profile)load().catch(()=>{})},1500)});
})();

(()=>{
  const loadScript=(src,id,onload)=>{if(document.getElementById(id)){onload?.();return}const s=document.createElement('script');s.id=id;s.src=src;s.onload=()=>onload?.();s.onerror=()=>console.error('BAMCO module load failed:',src);document.body.appendChild(s)};
  const boot=()=>loadScript('vehicle-management-20260907.js?v=20260907-1','bamcoVehicleManagement',()=>loadScript('vehicle-template-bootstrap-20260907.js?v=20260907-1','bamcoVehicleTemplate'));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
