-- Secure documents library + work sites/credentials.
create table if not exists public.document_categories(
 id bigint generated by default as identity primary key,
 title text not null check(length(btrim(title)) between 1 and 160), description text,
 sort_order integer not null default 0, created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists document_categories_sort_idx on public.document_categories(sort_order,id);

create table if not exists public.documents(
 id bigint generated by default as identity primary key,
 category_id bigint not null references public.document_categories(id) on delete cascade,
 title text not null check(length(btrim(title)) between 1 and 220), description text,
 original_file_name text not null check(length(btrim(original_file_name)) between 1 and 512),
 storage_path text not null unique, mime_type text not null, file_size bigint not null check(file_size>=0),
 version integer not null default 1 check(version>0), created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists documents_category_idx on public.documents(category_id,created_at desc);
create index if not exists documents_title_idx on public.documents(lower(title));

create or replace function private.is_safe_http_url(p_url text) returns boolean
language sql immutable set search_path='' as $$
 select coalesce(p_url ~* '^https?://[^[:space:]/?#]+(?::[0-9]{1,5})?(?:[/?#][^[:space:]]*)?$',false)
$$;

create table if not exists public.site_definitions(
 id bigint generated by default as identity primary key,
 kind text not null check(kind in('organization','personal')),
 owner_user_id uuid references public.profiles(id) on delete cascade,
 title text not null check(length(btrim(title)) between 1 and 200),
 url text not null check(private.is_safe_http_url(url)), description text, category text, icon text,
 scope text not null default 'all' check(scope in('all','selected','owner')), active boolean not null default true,
 created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint site_definition_kind_scope_check check(
  (kind='organization' and owner_user_id is null and scope in('all','selected')) or
  (kind='personal' and owner_user_id is not null and scope='owner')));
create index if not exists site_definitions_kind_idx on public.site_definitions(kind,active,id);
create index if not exists site_definitions_owner_idx on public.site_definitions(owner_user_id) where owner_user_id is not null;

create table if not exists public.site_assignments(
 site_id bigint not null references public.site_definitions(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 created_at timestamptz not null default now(), primary key(site_id,user_id));
create index if not exists site_assignments_user_idx on public.site_assignments(user_id,site_id);

create table if not exists public.user_site_credentials(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 site_id bigint not null references public.site_definitions(id) on delete cascade,
 username_ciphertext text not null, username_iv text not null,
 password_ciphertext text not null, password_iv text not null,
 key_version smallint not null default 1 check(key_version>0), notes text,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,site_id));
create index if not exists user_site_credentials_user_idx on public.user_site_credentials(user_id,site_id);

create table if not exists public.security_audit_log(
 id bigint generated by default as identity primary key,
 user_id uuid references public.profiles(id) on delete set null,
 action text not null, target_type text not null, target_id text,
 metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists security_audit_user_idx on public.security_audit_log(user_id,created_at desc);
create index if not exists security_audit_action_idx on public.security_audit_log(action,created_at desc);

create or replace function private.feature_touch_updated_at() returns trigger language plpgsql set search_path='' as $$
begin new.updated_at=now();return new;end $$;
drop trigger if exists document_categories_touch on public.document_categories;
create trigger document_categories_touch before update on public.document_categories for each row execute function private.feature_touch_updated_at();
drop trigger if exists documents_touch on public.documents;
create trigger documents_touch before update on public.documents for each row execute function private.feature_touch_updated_at();
drop trigger if exists site_definitions_touch on public.site_definitions;
create trigger site_definitions_touch before update on public.site_definitions for each row execute function private.feature_touch_updated_at();
drop trigger if exists user_site_credentials_touch on public.user_site_credentials;
create trigger user_site_credentials_touch before update on public.user_site_credentials for each row execute function private.feature_touch_updated_at();

create or replace function private.write_feature_audit(p_user uuid,p_action text,p_target_type text,p_target_id text,p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path='' as $$
begin insert into public.security_audit_log(user_id,action,target_type,target_id,metadata)
values(p_user,p_action,p_target_type,p_target_id,coalesce(p_metadata,'{}'::jsonb));end $$;
revoke all on function private.write_feature_audit(uuid,text,text,text,jsonb) from public,anon,authenticated;

create or replace function private.audit_category_changes() returns trigger language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();begin
 if auth.role()='service_role' then if tg_op='DELETE' then return old;else return new;end if;end if;
 if tg_op='INSERT' then perform private.write_feature_audit(actor,'category_create','document_category',new.id::text,jsonb_build_object('title',new.title));return new;
 elsif tg_op='UPDATE' then perform private.write_feature_audit(actor,'category_update','document_category',new.id::text,jsonb_build_object('title',new.title));return new;
 else perform private.write_feature_audit(actor,'category_delete','document_category',old.id::text,jsonb_build_object('title',old.title));return old;end if;
end $$;
drop trigger if exists document_categories_audit on public.document_categories;
create trigger document_categories_audit after insert or update or delete on public.document_categories for each row execute function private.audit_category_changes();

create or replace function private.audit_site_changes() returns trigger language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();begin
 if auth.role()='service_role' then if tg_op='DELETE' then return old;else return new;end if;end if;
 if tg_op='INSERT' then perform private.write_feature_audit(actor,'site_create','site_definition',new.id::text,jsonb_build_object('kind',new.kind,'title',new.title));return new;
 elsif tg_op='UPDATE' then perform private.write_feature_audit(actor,'site_update','site_definition',new.id::text,jsonb_build_object('kind',new.kind,'title',new.title));return new;
 else perform private.write_feature_audit(actor,'site_delete','site_definition',old.id::text,jsonb_build_object('kind',old.kind,'title',old.title));return old;end if;
end $$;
drop trigger if exists site_definitions_audit on public.site_definitions;
create trigger site_definitions_audit after insert or update or delete on public.site_definitions for each row execute function private.audit_site_changes();

alter table public.document_categories enable row level security;
alter table public.documents enable row level security;
alter table public.site_definitions enable row level security;
alter table public.site_assignments enable row level security;
alter table public.user_site_credentials enable row level security;
alter table public.security_audit_log enable row level security;

drop policy if exists document_categories_read on public.document_categories;
create policy document_categories_read on public.document_categories for select to authenticated using((select private.has_account()));
drop policy if exists document_categories_manager_insert on public.document_categories;
create policy document_categories_manager_insert on public.document_categories for insert to authenticated with check((select private.is_manager()) and created_by=(select auth.uid()));
drop policy if exists document_categories_manager_update on public.document_categories;
create policy document_categories_manager_update on public.document_categories for update to authenticated using((select private.is_manager())) with check((select private.is_manager()));
drop policy if exists document_categories_manager_delete on public.document_categories;
create policy document_categories_manager_delete on public.document_categories for delete to authenticated using((select private.is_manager()));

drop policy if exists documents_read on public.documents;
create policy documents_read on public.documents for select to authenticated using((select private.has_account()));
drop policy if exists documents_manager_insert on public.documents;
create policy documents_manager_insert on public.documents for insert to authenticated with check((select private.is_manager()) and created_by=(select auth.uid()));
drop policy if exists documents_manager_update on public.documents;
create policy documents_manager_update on public.documents for update to authenticated using((select private.is_manager())) with check((select private.is_manager()));
drop policy if exists documents_manager_delete on public.documents;
create policy documents_manager_delete on public.documents for delete to authenticated using((select private.is_manager()));

drop policy if exists site_definitions_read on public.site_definitions;
create policy site_definitions_read on public.site_definitions for select to authenticated using(
 (select private.has_account()) and ((select private.is_manager()) or
 (kind='personal' and owner_user_id=(select auth.uid())) or
 (kind='organization' and active and (scope='all' or (scope='selected' and exists(select 1 from public.site_assignments sa where sa.site_id=site_definitions.id and sa.user_id=(select auth.uid())))))));
drop policy if exists site_definitions_insert on public.site_definitions;
create policy site_definitions_insert on public.site_definitions for insert to authenticated with check(
 ((select private.is_manager()) and kind='organization' and created_by=(select auth.uid())) or
 (kind='personal' and owner_user_id=(select auth.uid()) and created_by=(select auth.uid()) and scope='owner' and active));
drop policy if exists site_definitions_update on public.site_definitions;
create policy site_definitions_update on public.site_definitions for update to authenticated using(
 ((select private.is_manager()) and kind='organization') or(kind='personal' and owner_user_id=(select auth.uid()))) with check(
 ((select private.is_manager()) and kind='organization' and owner_user_id is null and scope in('all','selected')) or
 (kind='personal' and owner_user_id=(select auth.uid()) and scope='owner'));
drop policy if exists site_definitions_delete on public.site_definitions;
create policy site_definitions_delete on public.site_definitions for delete to authenticated using(
 ((select private.is_manager()) and kind='organization') or(kind='personal' and owner_user_id=(select auth.uid())));

drop policy if exists site_assignments_read on public.site_assignments;
create policy site_assignments_read on public.site_assignments for select to authenticated using((select private.is_manager()) or user_id=(select auth.uid()));
drop policy if exists site_assignments_manager_insert on public.site_assignments;
create policy site_assignments_manager_insert on public.site_assignments for insert to authenticated with check((select private.is_manager()));
drop policy if exists site_assignments_manager_update on public.site_assignments;
create policy site_assignments_manager_update on public.site_assignments for update to authenticated using((select private.is_manager())) with check((select private.is_manager()));
drop policy if exists site_assignments_manager_delete on public.site_assignments;
create policy site_assignments_manager_delete on public.site_assignments for delete to authenticated using((select private.is_manager()));

drop policy if exists audit_manager_read on public.security_audit_log;
create policy audit_manager_read on public.security_audit_log for select to authenticated using((select private.is_manager()));

revoke all on public.user_site_credentials from anon,authenticated;
grant select,insert,update,delete on public.document_categories,public.documents,public.site_definitions,public.site_assignments to authenticated;
grant select on public.security_audit_log to authenticated;
grant all on public.document_categories,public.documents,public.site_definitions,public.site_assignments,public.user_site_credentials,public.security_audit_log to service_role;
grant usage,select on sequence public.document_categories_id_seq to authenticated,service_role;
grant usage,select on sequence public.documents_id_seq to authenticated,service_role;
grant usage,select on sequence public.site_definitions_id_seq to authenticated,service_role;
grant usage,select on sequence public.user_site_credentials_id_seq to service_role;
grant usage,select on sequence public.security_audit_log_id_seq to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('documents-private','documents-private',false,26214400,array[
 'application/pdf','image/png','image/jpeg','image/webp','text/plain','text/csv','application/vnd.ms-excel',
 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists documents_storage_read on storage.objects;
create policy documents_storage_read on storage.objects for select to authenticated using(bucket_id='documents-private' and(select private.has_account()));
drop policy if exists documents_storage_manager_insert on storage.objects;
create policy documents_storage_manager_insert on storage.objects for insert to authenticated with check(bucket_id='documents-private' and(select private.is_manager()));
drop policy if exists documents_storage_manager_update on storage.objects;
create policy documents_storage_manager_update on storage.objects for update to authenticated using(bucket_id='documents-private' and(select private.is_manager())) with check(bucket_id='documents-private' and(select private.is_manager()));
drop policy if exists documents_storage_manager_delete on storage.objects;
create policy documents_storage_manager_delete on storage.objects for delete to authenticated using(bucket_id='documents-private' and(select private.is_manager()));

-- A random AES-256 key is created server-side only. The actual value is never committed.
do $$begin
 if not exists(select 1 from vault.secrets where name='bamco_credential_aes_key') then
  perform vault.create_secret(encode(extensions.gen_random_bytes(32),'base64'),'bamco_credential_aes_key','AES-256-GCM key for BAMCO site credentials; server-only');
 end if;
end$$;
create or replace function public.credential_server_key() returns text language plpgsql stable security definer set search_path='' as $$
declare v_key text;begin
 if auth.role()<>'service_role' then raise exception 'دسترسی مجاز نیست';end if;
 select decrypted_secret into v_key from vault.decrypted_secrets where name='bamco_credential_aes_key' limit 1;
 if v_key is null then raise exception 'کلید رمزنگاری تنظیم نشده است';end if;return v_key;
end$$;
revoke all on function public.credential_server_key() from public,anon,authenticated;
grant execute on function public.credential_server_key() to service_role;
