-- Portal-only communication, configurable task labels and editable request workflow.
create table if not exists public.message_templates (
  id bigint generated by default as identity primary key,
  template_key text not null unique,
  body_text text not null default '',
  updated_at timestamptz not null default now()
);
alter table public.message_templates enable row level security;
drop policy if exists "message templates readable" on public.message_templates;
create policy "message templates readable" on public.message_templates for select to authenticated using (true);
drop policy if exists "managers manage message templates" on public.message_templates;
create policy "managers manage message templates" on public.message_templates for all to authenticated using ((select private.is_manager())) with check ((select private.is_manager()));
insert into public.message_templates(template_key,body_text)
select template_key,coalesce(body_html,'') from public.email_templates
where to_regclass('public.email_templates') is not null
on conflict(template_key) do nothing;

create table if not exists public.task_field_options (
  id bigint generated by default as identity primary key,
  field_type text not null check(field_type in ('status','priority','due_state')),
  value text not null,
  label text not null,
  system_key text,
  sort_order integer not null default 100,
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(field_type,value)
);
alter table public.tasks drop constraint if exists tasks_status_check;
alter table public.tasks drop constraint if exists tasks_priority_check;
alter table public.task_field_options enable row level security;
create policy "options readable" on public.task_field_options for select to authenticated using (true);
create policy "managers manage options" on public.task_field_options for all to authenticated using ((select private.is_manager())) with check ((select private.is_manager()));
insert into public.task_field_options(field_type,value,label,system_key,sort_order) values
 ('status','ثبت شده','ثبت شده','registered',10),('status','منتظر پاسخ','منتظر پاسخ','waiting',20),('status','در حال انجام','در حال انجام','active',30),('status','انجام شده','انجام شده','completed',40),
 ('priority','کم','کم','low',10),('priority','متوسط','متوسط','medium',20),('priority','فوری','فوری','urgent',30),
 ('due_state','فاقد شرایط دیرکرد','فاقد شرایط دیرکرد','none',10),('due_state','دوره هشدار','دوره هشدار','warning',20),('due_state','دیرکرد','دیرکرد','overdue',30)
on conflict(field_type,value) do nothing;

alter table public.change_requests add column if not exists revision_count integer not null default 0;
alter table public.change_requests add column if not exists resubmitted_at timestamptz;

drop function if exists public.review_change_request(bigint,text,text);
drop function if exists public.review_change_request(bigint,text,text,jsonb);
create function public.review_change_request(p_request_id bigint,p_decision text,p_manager_note text default null,p_final_data jsonb default null)
returns void language plpgsql security invoker set search_path=''
as $$
declare r public.change_requests%rowtype; payload jsonb; new_task_id bigint;
begin
  if not (select private.is_manager()) then raise exception 'دسترسی مدیر لازم است'; end if;
  if p_decision not in ('approved','rejected','needs_revision') then raise exception 'تصمیم نامعتبر است'; end if;
  select * into r from public.change_requests where id=p_request_id and request_status='pending' for update;
  if not found then raise exception 'درخواست باز پیدا نشد'; end if;
  payload=coalesce(p_final_data,r.proposed_data);
  if p_decision='approved' then
    if r.request_type='create' then
      insert into public.tasks(title,description,owner_id,status,priority,start_date,done_date,due_date,reminder_days,manager_notes,created_by,archived,archived_at)
      values(payload->>'title',coalesce(payload->>'description',''),coalesce(nullif(payload->>'owner_id','')::uuid,r.requested_by),coalesce(payload->>'status','ثبت شده'),coalesce(payload->>'priority','متوسط'),nullif(payload->>'start_date','')::date,nullif(payload->>'done_date','')::date,nullif(payload->>'due_date','')::date,coalesce((payload->>'reminder_days')::integer,0),coalesce(payload->>'manager_notes',''),auth.uid(),coalesce((payload->>'archived')::boolean,false),case when coalesce((payload->>'archived')::boolean,false) then now() end) returning id into new_task_id;
      update public.change_requests set task_id=new_task_id where id=r.id;
    elsif r.request_type='update' then
      update public.tasks set title=coalesce(payload->>'title',title),description=coalesce(payload->>'description',description),owner_id=coalesce(nullif(payload->>'owner_id','')::uuid,owner_id),status=coalesce(payload->>'status',status),priority=coalesce(payload->>'priority',priority),start_date=case when payload?'start_date' then nullif(payload->>'start_date','')::date else start_date end,done_date=case when payload?'done_date' then nullif(payload->>'done_date','')::date else done_date end,due_date=case when payload?'due_date' then nullif(payload->>'due_date','')::date else due_date end,reminder_days=coalesce((payload->>'reminder_days')::integer,reminder_days),manager_notes=coalesce(payload->>'manager_notes',manager_notes) where id=r.task_id;
    elsif r.request_type='complete' then update public.tasks set status='انجام شده',done_date=coalesce(nullif(payload->>'done_date','')::date,current_date),archived=true,archived_at=now() where id=r.task_id;
    end if;
  end if;
  update public.change_requests set proposed_data=payload,request_status=p_decision,manager_note=p_manager_note,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id;
end $$;
revoke all on function public.review_change_request(bigint,text,text,jsonb) from public,anon;
grant execute on function public.review_change_request(bigint,text,text,jsonb) to authenticated;

create or replace function public.resubmit_change_request(p_request_id bigint,p_proposed_data jsonb)
returns void language plpgsql security invoker set search_path=''
as $$ begin
  update public.change_requests set proposed_data=p_proposed_data,request_status='pending',revision_count=revision_count+1,resubmitted_at=now(),reviewed_by=null,reviewed_at=null
  where id=p_request_id and requested_by=auth.uid() and request_status='needs_revision';
  if not found then raise exception 'درخواست قابل اصلاح پیدا نشد'; end if;
end $$;
revoke all on function public.resubmit_change_request(bigint,jsonb) from public,anon;
grant execute on function public.resubmit_change_request(bigint,jsonb) to authenticated;
