-- BAMCO phase 1: canonical task rules, configurable approvals and immutable audit.
-- Designed to be applied first on the staging project.

create extension if not exists pgcrypto;

alter table public.task_statuses
  add column if not exists color text not null default '#6f8f84',
  add column if not exists allows_start_date boolean not null default true,
  add column if not exists allows_due_date boolean not null default true,
  add column if not exists archivable boolean not null default false,
  add column if not exists is_system boolean not null default false;

alter table public.priorities
  add column if not exists color text not null default '#6f8f84';

insert into public.task_statuses(key,label,sort_order,active,color,allows_start_date,allows_due_date,archivable,is_system)
values
 ('registered','ثبت شده',10,true,'#5f7f75',false,false,false,true),
 ('doing','در حال انجام',20,true,'#2f80ed',true,true,false,true),
 ('waiting','منتظر پاسخ',30,true,'#8b949e',true,false,false,true),
 ('done','انجام شده',40,true,'#27ae60',true,true,true,true),
 ('paused','متوقف شده',50,false,'#b7791f',true,true,false,true),
 ('cancelled','لغو شده',60,false,'#9b2c2c',true,true,true,true)
on conflict (key) do update set label=excluded.label,sort_order=excluded.sort_order,
 color=excluded.color,allows_start_date=excluded.allows_start_date,
 allows_due_date=excluded.allows_due_date,archivable=excluded.archivable,is_system=excluded.is_system;

insert into public.priorities(key,label,sort_order,active,color)
values ('urgent','فوری',10,true,'#ef5350'),('medium','متوسط',20,true,'#f2a93b'),('low','کم',30,true,'#39a96b')
on conflict (key) do update set label=excluded.label,sort_order=excluded.sort_order,color=excluded.color;

alter table public.tasks add column if not exists change_reason text;

create or replace function private.enforce_task_rules()
returns trigger language plpgsql set search_path='' as $$
begin
  if new.status='ثبت شده' then
    new.start_date=null; new.due_date=null; new.done_date=null;
  elsif new.status='منتظر پاسخ' then
    new.due_date=null; new.done_date=null;
  elsif new.status='انجام شده' and new.done_date is null then
    new.done_date=current_date;
  end if;
  if new.due_date is not null and new.start_date is not null and new.due_date < new.start_date then
    raise exception 'تاریخ پایان نمی‌تواند قبل از تاریخ شروع باشد';
  end if;
  if new.done_date is not null and new.status <> 'انجام شده' then
    raise exception 'تاریخ انجام فقط برای وظیفه انجام‌شده مجاز است';
  end if;
  new.last_updated_at=now();
  if tg_op='UPDATE' then new.row_version=old.row_version+1; end if;
  return new;
end $$;

drop trigger if exists trg_enforce_task_rules on public.tasks;
create trigger trg_enforce_task_rules before insert or update on public.tasks
for each row execute function private.enforce_task_rules();

alter table public.change_requests drop constraint if exists change_requests_request_type_check;
alter table public.change_requests add constraint change_requests_request_type_check
 check(request_type in ('create','update','status','priority','description','complete','delete','due_date'));
alter table public.change_requests drop constraint if exists change_requests_request_status_check;
alter table public.change_requests add constraint change_requests_request_status_check
 check(request_status in ('draft','pending','in_review','needs_revision','approved','rejected','cancelled'));
alter table public.change_requests
 add column if not exists current_stage smallint not null default 1,
 add column if not exists completed_at timestamptz,
 add column if not exists final_data jsonb,
 add column if not exists applied_task_id bigint references public.tasks(id);

create table if not exists public.approval_chains(
 id bigint generated by default as identity primary key,
 name text not null unique,
 active boolean not null default true,
 is_default boolean not null default false,
 created_at timestamptz not null default now(),
 created_by uuid references public.profiles(id)
);
create table if not exists public.approval_chain_members(
 chain_id bigint not null references public.approval_chains(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 primary key(chain_id,user_id)
);
create table if not exists public.approval_chain_stages(
 id bigint generated by default as identity primary key,
 chain_id bigint not null references public.approval_chains(id) on delete cascade,
 stage_no smallint not null check(stage_no>0),
 title text not null,
 approval_rule text not null default 'any' check(approval_rule in ('any','all')),
 unique(chain_id,stage_no)
);
create table if not exists public.approval_stage_approvers(
 stage_id bigint not null references public.approval_chain_stages(id) on delete cascade,
 approver_id uuid not null references public.profiles(id) on delete cascade,
 primary key(stage_id,approver_id)
);
create table if not exists public.request_approval_steps(
 id bigint generated by default as identity primary key,
 request_id bigint not null references public.change_requests(id) on delete cascade,
 stage_id bigint not null references public.approval_chain_stages(id),
 approver_id uuid not null references public.profiles(id),
 decision text not null default 'pending' check(decision in ('pending','approved','rejected','needs_revision')),
 note text,
 decided_at timestamptz,
 unique(request_id,stage_id,approver_id)
);

create table if not exists public.change_request_events(
 id bigint generated by default as identity primary key,
 request_id bigint not null references public.change_requests(id) on delete cascade,
 actor_id uuid references public.profiles(id),
 event_type text not null,
 note text,
 snapshot jsonb,
 created_at timestamptz not null default now()
);
alter table public.change_request_events drop constraint if exists change_request_events_event_type_check;
alter table public.change_request_events add constraint change_request_events_event_type_check
 check(event_type in ('drafted','submitted','routed','approved','corrected_and_approved','rejected','needs_revision','resubmitted','applied','cancelled'));

alter table public.task_history
 add column if not exists source_path text not null default 'direct',
 add column if not exists reason text,
 add column if not exists correlation_id uuid not null default gen_random_uuid();

create or replace function private.audit_task_change()
returns trigger language plpgsql security definer set search_path='' as $$
declare k text; old_j jsonb; new_j jsonb; actor uuid; req bigint;
begin
  actor=auth.uid();
  req=nullif(current_setting('app.request_id',true),'')::bigint;
  if tg_op='INSERT' then
    insert into public.task_history(task_id,action,new_data,actor_id,request_id,source_path,reason)
    values(new.id,'created',to_jsonb(new),actor,req,coalesce(nullif(current_setting('app.source_path',true),''),'direct'),new.change_reason);
    return new;
  elsif tg_op='DELETE' then
    insert into public.task_history(task_id,action,old_data,actor_id,request_id,source_path,reason)
    values(old.id,'deleted',to_jsonb(old),actor,req,coalesce(nullif(current_setting('app.source_path',true),''),'direct'),old.change_reason);
    return old;
  end if;
  old_j=to_jsonb(old); new_j=to_jsonb(new);
  for k in select jsonb_object_keys(new_j) loop
    if old_j->k is distinct from new_j->k and k not in ('last_updated_at','row_version','change_reason') then
      insert into public.task_history(task_id,action,field_name,old_value,new_value,old_data,new_data,actor_id,request_id,source_path,reason)
      values(new.id,'updated',k,old_j->k,new_j->k,old_j,new_j,actor,req,coalesce(nullif(current_setting('app.source_path',true),''),'direct'),new.change_reason);
    end if;
  end loop;
  return new;
end $$;

drop trigger if exists trg_task_audit on public.tasks;
create trigger trg_task_audit after insert or update or delete on public.tasks
for each row execute function private.audit_task_change();

create or replace function public.task_temporal_state(t public.tasks, at_date date default current_date)
returns text language sql stable set search_path='' as $$
 select case
  when t.status='منتظر پاسخ' or t.due_date is null then 'فاقد شرایط دیرکرد'
  when t.status='انجام شده' then 'فاقد شرایط دیرکرد'
  when t.due_date < at_date then 'دیرکرد'
  when t.due_date <= at_date + greatest(t.reminder_days,0) then 'هشدار'
  else 'عادی' end
$$;

create or replace view public.tasks_with_state with (security_invoker=true) as
select t.*, public.task_temporal_state(t,current_date) as temporal_state,
 (t.start_date is null or (t.due_date is null and t.status<>'منتظر پاسخ')) as unscheduled
from public.tasks t;

alter table public.approval_chains enable row level security;
alter table public.approval_chain_members enable row level security;
alter table public.approval_chain_stages enable row level security;
alter table public.approval_stage_approvers enable row level security;
alter table public.request_approval_steps enable row level security;

create policy approval_chains_read on public.approval_chains for select to authenticated using(true);
create policy approval_chains_manage on public.approval_chains for all to authenticated using((select private.is_manager())) with check((select private.is_manager()));
create policy approval_members_read on public.approval_chain_members for select to authenticated using(true);
create policy approval_members_manage on public.approval_chain_members for all to authenticated using((select private.is_manager())) with check((select private.is_manager()));
create policy approval_stages_read on public.approval_chain_stages for select to authenticated using(true);
create policy approval_stages_manage on public.approval_chain_stages for all to authenticated using((select private.is_manager())) with check((select private.is_manager()));
create policy approval_approvers_read on public.approval_stage_approvers for select to authenticated using(true);
create policy approval_approvers_manage on public.approval_stage_approvers for all to authenticated using((select private.is_manager())) with check((select private.is_manager()));
create policy request_steps_read on public.request_approval_steps for select to authenticated using(
 approver_id=(select auth.uid()) or (select private.is_manager()) or exists(select 1 from public.change_requests r where r.id=request_id and r.requested_by=(select auth.uid()))
);
create policy request_steps_manage on public.request_approval_steps for all to authenticated using((select private.is_manager())) with check((select private.is_manager()));

revoke insert,update,delete on public.task_history from authenticated;
grant select on public.tasks_with_state to authenticated;
grant select on public.approval_chains,public.approval_chain_members,public.approval_chain_stages,public.approval_stage_approvers,public.request_approval_steps to authenticated;
grant insert,update,delete on public.approval_chains,public.approval_chain_members,public.approval_chain_stages,public.approval_stage_approvers to authenticated;
grant usage,select on all sequences in schema public to authenticated;
