create table if not exists public.vehicle_permanent_records (
  id bigint generated by default as identity primary key,
  plate_number text, vehicle_type text, body_color text, chassis_number text,
  handover_from text, handover_to text, assignment_date text, current_location text,
  documents_status text, remote_count bigint, insurance_expiry_date text,
  last_mileage bigint, receipt_reason text, return_receiver text,
  return_deliverer text, return_date text, notes text, form_path text,
  created_by uuid references public.profiles(id) default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.vehicle_temporary_records (
  id bigint generated by default as identity primary key,
  plate_number text, vehicle_type text, body_color text, chassis_number text,
  handover_from text, handover_to text, assignment_date text, exit_time text,
  entry_time text, last_mileage bigint, fuel_status text, receipt_reason text,
  notes text, created_by uuid references public.profiles(id) default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.vehicle_permanent_records enable row level security;
alter table public.vehicle_temporary_records enable row level security;
grant select,insert,update,delete on public.vehicle_permanent_records to authenticated;
grant select,insert,update,delete on public.vehicle_temporary_records to authenticated;
grant usage,select on sequence public.vehicle_permanent_records_id_seq to authenticated;
grant usage,select on sequence public.vehicle_temporary_records_id_seq to authenticated;
drop policy if exists vehicle_permanent_manager_all on public.vehicle_permanent_records;
drop policy if exists vehicle_permanent_manager_select on public.vehicle_permanent_records;
drop policy if exists vehicle_permanent_manager_insert on public.vehicle_permanent_records;
drop policy if exists vehicle_permanent_manager_update on public.vehicle_permanent_records;
drop policy if exists vehicle_permanent_manager_delete on public.vehicle_permanent_records;
create policy vehicle_permanent_manager_all on public.vehicle_permanent_records for all to authenticated using ((select private.is_manager())) with check ((select private.is_manager()));
drop policy if exists vehicle_temporary_manager_all on public.vehicle_temporary_records;
drop policy if exists vehicle_temporary_manager_select on public.vehicle_temporary_records;
drop policy if exists vehicle_temporary_manager_insert on public.vehicle_temporary_records;
drop policy if exists vehicle_temporary_manager_update on public.vehicle_temporary_records;
drop policy if exists vehicle_temporary_manager_delete on public.vehicle_temporary_records;
create policy vehicle_temporary_manager_all on public.vehicle_temporary_records for all to authenticated using ((select private.is_manager())) with check ((select private.is_manager()));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('vehicle-forms','vehicle-forms',false,20971520,array['application/pdf','image/jpeg','image/png']) on conflict(id) do update set public=false,file_size_limit=20971520,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists vehicle_forms_manager_select on storage.objects;
create policy vehicle_forms_manager_select on storage.objects for select to authenticated using(bucket_id='vehicle-forms' and (select private.is_manager()));
drop policy if exists vehicle_forms_manager_insert on storage.objects;
create policy vehicle_forms_manager_insert on storage.objects for insert to authenticated with check(bucket_id='vehicle-forms' and (select private.is_manager()));
drop policy if exists vehicle_forms_manager_update on storage.objects;
create policy vehicle_forms_manager_update on storage.objects for update to authenticated using(bucket_id='vehicle-forms' and (select private.is_manager())) with check(bucket_id='vehicle-forms' and (select private.is_manager()));
drop policy if exists vehicle_forms_manager_delete on storage.objects;
create policy vehicle_forms_manager_delete on storage.objects for delete to authenticated using(bucket_id='vehicle-forms' and (select private.is_manager()));
